-- MySQL Script generated by MySQL Workbench
-- 11/21/14 10:20:19
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ordertracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordertracker` DEFAULT CHARACTER SET utf8 ;
USE `ordertracker` ;

-- -----------------------------------------------------
-- Table `ordertracker`.`orderallamount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`orderallamount` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`orderallamount` (
  `Suborderid` VARCHAR(45) NOT NULL,
  `COD_NON_COD_Credit` DECIMAL(18,2) NULL DEFAULT '0.00',
  `COD_NON_COD_Debit` DECIMAL(18,2) NULL DEFAULT '0.00',
  `Incentive` DECIMAL(18,2) NULL DEFAULT '0.00',
  `Disincentive` DECIMAL(18,2) NULL DEFAULT '0.00',
  `COD_NCOD_Wrong_faulty_Debit` DECIMAL(18,2) NULL DEFAULT '0.00',
  `Stock_Out_Commission` DECIMAL(18,2) NULL DEFAULT '0.00',
  `Courier_lost_vendor` DECIMAL(18,2) NULL DEFAULT '0.00',
  `COD_Non_COD_Frgt_post_ship` DECIMAL(18,2) NULL DEFAULT '0.00',
  `RTO_Conflict` DECIMAL(18,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`Suborderid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordertracker`.`orderdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`orderdetails` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`orderdetails` (
  `SubOrderID` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `Remark` VARCHAR(128) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `Amount` DECIMAL(18,2) NULL DEFAULT NULL,
  `CreationDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`SubOrderID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordertracker`.`orderhos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`orderhos` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`orderhos` (
  `suborderid` VARCHAR(45) NOT NULL,
  `Sku` VARCHAR(100) NULL DEFAULT NULL,
  `Supc` VARCHAR(100) NULL DEFAULT NULL,
  `AWB` VARCHAR(100) NULL DEFAULT NULL,
  `Ref` VARCHAR(100) NULL DEFAULT NULL,
  `CreationDate` DATETIME NULL DEFAULT NULL,
  `hosno` VARCHAR(45) NULL DEFAULT NULL,
  `hosdate` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`suborderid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordertracker`.`orderpacked`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`orderpacked` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`orderpacked` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `suborderid` VARCHAR(45) NOT NULL DEFAULT '',
  `Category` VARCHAR(100) NULL DEFAULT NULL,
  `Courier` VARCHAR(100) NULL DEFAULT NULL,
  `Product` VARCHAR(100) NULL DEFAULT NULL,
  `Reference_Code` VARCHAR(100) NULL DEFAULT NULL,
  `SKU_Code` VARCHAR(100) NULL DEFAULT NULL,
  `AWB_Number` VARCHAR(100) NULL DEFAULT NULL,
  `Order_Verified_Date` DATETIME NULL DEFAULT NULL,
  `Order_Created_Date` DATETIME NULL DEFAULT NULL,
  `Customer_Name` VARCHAR(100) NULL DEFAULT NULL,
  `Shipping_Name` VARCHAR(100) NULL DEFAULT NULL,
  `City` VARCHAR(100) NULL DEFAULT NULL,
  `State` VARCHAR(100) NULL DEFAULT NULL,
  `PIN_Code` VARCHAR(100) NULL DEFAULT NULL,
  `Selling_Price_Per_Item` VARCHAR(100) NULL DEFAULT NULL,
  `IMEI_SERIAL` VARCHAR(100) NULL DEFAULT NULL,
  `PromisedShipDate` DATETIME NULL DEFAULT NULL,
  `MRP` VARCHAR(100) NULL DEFAULT NULL,
  `InvoiceCode` VARCHAR(100) NULL DEFAULT NULL,
  `CreationDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `suborderid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordertracker`.`orderpayment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`orderpayment` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`orderpayment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `suborderid` VARCHAR(45) NULL DEFAULT NULL,
  `customername` VARCHAR(100) NULL DEFAULT NULL,
  `web_sale_price` VARCHAR(100) NULL DEFAULT NULL,
  `cash_back` VARCHAR(100) NULL DEFAULT NULL,
  `emi` VARCHAR(100) NULL DEFAULT NULL,
  `merchant_cut` VARCHAR(100) NULL DEFAULT NULL,
  `fulfillment_fee` VARCHAR(100) NULL DEFAULT NULL,
  `fulfillment_fee_waiver` VARCHAR(100) NULL DEFAULT NULL,
  `marketing_fee` VARCHAR(100) NULL DEFAULT NULL,
  `payment_collection_fee` VARCHAR(100) NULL DEFAULT NULL,
  `courier_fee` VARCHAR(100) NULL DEFAULT NULL,
  `comm` VARCHAR(100) NULL DEFAULT NULL,
  `sku_code` VARCHAR(100) NULL DEFAULT NULL,
  `shipped_return_date` VARCHAR(100) NULL DEFAULT NULL,
  `delivered_date` VARCHAR(100) NULL DEFAULT NULL,
  `shipping_method_code` VARCHAR(100) NULL DEFAULT NULL,
  `courier` VARCHAR(100) NULL DEFAULT NULL,
  `awb_number` VARCHAR(100) NULL DEFAULT NULL,
  `amount` DECIMAL(18,2) NULL DEFAULT NULL,
  `other_applications` VARCHAR(100) NULL DEFAULT NULL,
  `creationdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordertracker`.`orderstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`orderstatus` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`orderstatus` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `statusname` VARCHAR(45) NULL DEFAULT NULL,
  `priority` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordertracker`.`ordertransection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`ordertransection` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`ordertransection` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `suborderid` VARCHAR(45) NOT NULL,
  `remark` VARCHAR(128) NULL DEFAULT NULL,
  `creationDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32961
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordertracker`.`paymentmap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`paymentmap` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`paymentmap` (
  `ActualField` VARCHAR(100) NOT NULL,
  `Tablefield` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ActualField`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordertracker`.`paymentstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`paymentstatus` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`paymentstatus` (
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `remark` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordertracker`.`usermaster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordertracker`.`usermaster` ;

CREATE TABLE IF NOT EXISTS `ordertracker`.`usermaster` (
  `username` VARCHAR(50) NOT NULL,
  `Pass` VARCHAR(45) NULL DEFAULT NULL,
  `UserType` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedOn` DATETIME NULL DEFAULT NULL,
  `UpdatedOn` DATETIME NULL DEFAULT NULL,
  `Active` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
